version: "3"

services:
  app:
    build: .
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/app"
    depends_on:
      - "postgres"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
