version: '3'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    # logging:
    # driver: none
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fastfeet}
      POSTGRES_DB: fastfeet

  app:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    command: bash -c 'yarn db:migrate && yarn dev'
    ports:
      - '3000:3000'
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    depends_on:
      - postgres

